notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#build"
    use_notice: true
    skip_join: true

language: python
addons:
  postgresql: "9.1"

install:
  - sudo apt-get update -qq
  - sudo apt-get install python-virtualenv curl yui-compressor
  - gem install --no-ri --no-rdoc compass -v 0.12.7
  - gem install --no-ri --no-rdoc sass -v 3.2.19
  # Now install the rest of the required Python packages:
  - CFLAGS="-O0" pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls
  # Create a basic general.yml file:
  - sed -r
    -e "s,(YNMP_DB_USER:) .*,\\1 'postgres',"
    -e "s,(SECRET_KEY:) '',\\1 'notatallsecret',"
    conf/general.yml-example > conf/general.yml

script:
  - coverage run --source=candidates,cached_counts,tasks,moderation_queue,official_documents,results --branch ./manage.py test
after_success:
  - coveralls
